from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^auth/register/$', views.register, name='register'),
    url(r'^auth/login/$', views.login, name='login'),
    url(r'^edit/delete_user/$', views.delete_user),
    url(r'^edit/update_user/$', views.update_user),
    url(r'^password/change_user_password/$', views.change_user_password),
    url(r'^password/forget_password/$', views.forget_password, name='forget_password'),
    url(r'^reset_password/(?P<token>.*)/$', views.reset_password, name='reset_password'),
    url(r'^auth/activate/(?P<token>.*)', views.activate),
    url(r'^users/viewusers/$', views.view_all_users),
    url(r'^users/viewuserprofile/$', views.view_user_profile),
    url(r'^users/add_user/$', views.add_user),
    url(r'^users/update_passcode/$', views.update_passcode),
    url(r'^users/viewpasscode/$', views.get_passcode),
    url(r'^users/confirmpasscode/$', views.confirm_passcode),
    url(r'^users/add_organisation_user/$', views.add_organisation_user),
    url(r'^users/vieworgusers/$', views.view_organisation_users),
    url(r'^create_form/$', views.create_form),
    url(r'^create_form_customer/$', views.customer_create_form),
    url(r'^termandconditions/$', views.get_terms_and_conditions),
    url(r'^privacypolicy/$', views.get_privacy_policy),
    url(r'^disclaimers/$', views.get_disclaimer),
    url(r'^editform/$', views.update_admin_modules),
    url(r'^formlisting/$', views.form_listing),
    url(r'^getexistingtemplates/$', views.get_existing_templates),
    url(r'^formdelete/$', views.delete_form),
    url(r'^viewtemplate/$', views.view_admin_template),
    url(r'^viewcustomerforms/(?P<form_id>\d+)/$', views.view_customer_form),
    url(r'^updatewelcomemoduleadmin/$', views.update_welcome_module_admin),
    url(r'^updateunlockmoduleadmin/$', views.update_unlock_module_admin),
    url(r'^updatesubmitmoduleadmin/$', views.update_submit_module_admin),
    url(r'^updatedropboxmoduleadmin/$', views.update_dropbox_module_admin),
    url(r'^updateemailmoduleadmin/$', views.update_email_module_admin),
    url(r'^updatedrivemoduleadmin/$', views.update_drive_module_admin),
    url(r'^getwelcomemoduleadmin/$', views.get_welcome_module_admin),
    url(r'^getunlockmoduleadmin/$', views.get_unlock_module_admin),
    url(r'^getsubmitmoduleadmin/$', views.get_submit_module_admin),
    url(r'^getemailmoduleadmin/$', views.get_email_module_admin),
    url(r'^getdropboxmoduleadmin/$', views.get_dropbox_module_admin),
    url(r'^getdrivemoduleadmin/$', views.get_drive_module_admin),
    url(r'^dropboxauthstart/$', views.dropbox_integration_start),
    url(r'^driveauthstart/$', views.drive_integration_start),
    url(r'^driveauthfinish/$', views.drive_integration_finish, name='finish_drive_integration'),
    url(r'^dropboxauthfinish/$', views.dropbox_integration_finish, name='finish_dropbox_integration'),
    url(r'^changeformstatus/$', views.change_form_status),
    url(r'^organisationforms/$', views.organisation_form_listing),
    url(r'^createcart/$', views.add_to_cart_for_customer_forms),
    url(r'^getcart/$', views.get_cart),
    url(r'^cancelitemcart/$', views.cancel_item_cart),
    url(r'^getsitedetails/$', views.get_site_details),
    url(r'^customerforms/$', views.customer_form_listing),
    url(r'^deletecustomerform/$', views.delete_customer_form),
    url(r'^editcustomerform/$', views.update_customer_forms),
    url(r'^getencodedformid/$', views.generate_encoded_form_id),
    url(r'^getformdata/$', views.render_form_data_by_link),
    url(r'^listfunctionalmodules/$', views.list_functional_modules),
    url(r'^submitformdata/$', views.submit_form_data),
    url(r'^viewsubmittedform/$', views.get_submit_form_data),
    url(r'^changestatustosubmit/$', views.change_status_to_submit),
    url(r'^getsubmittedforms/$', views.get_submitted_forms),
    url(r'^getusersondaterange/$', views.no_of_users_in_a_date_range),
    url(r'^uploadimage/$', views.upload_image_form_submit),
    url(r'^getfilledforms/$', views.get_all_filled_forms_from_published_forms),
    url(r'^makepayment/$', views.make_payment),
    url(r'^executepayment/$', views.execute_payment, name='exec_payment'),
    url(r'^updatetrialorpaid$', views.update_paid_or_trial_of_a_user),
    url(r'^configuration$', views.configuration_api),
    url(r'^upgradeaccount$', views.upgrade_now),
]
